GUARD-2926-add-shipstation-logging
skuvault-integrations/shipStationAccess pull request #10
Opened 2023-05-03 02:39 UTC by Victoria-SV

# Description
Tickets: [GUARD-2926]
Goal: to provide more content about the 401 error before throwing ShipStationUnauthorizedException.

## Background
Currently, we throw ShipStationUnauthorizedException exception without logging any additional information about the error. We need to log information before throwing and this would help us to diagnose why and which request returned the 401 Unauthorized error. 

## About the changes in this PR
Added logging by following the existing pattern.

Example log from unit testing:
```
2023-05-02 22:37:45 [Information] [shipstation]	Request to 'https://ssapi.shipstation.com/Orders/List?createDateStart=2023-04-23T02:37:39-00:00&createDateEnd=2023-05-03T02:37:39-00:00&pageSize=20&page=1' returned HTTP 401 Error with the response content: '401 Unauthorized'. Request Headers: Authorization: Basic ZjdkODFhZWE2Njg2NDk2MDhhMjAyOGE2NDQ5YmUwZTUyY2VhZDA4Yi1mMDE4LTRjNTgtOGJkYS1lMmIwNWVkZTNiNGM6Y2QyZjVhMmIwOTFmNDM2Yjg0NWQ4YmFiMmRjZjAyNDE=
, Response Headers: X-Rate-Limit-Limit: 40
X-Rate-Limit-Remaining: 40
X-Rate-Limit-Reset: 20
Connection: keep-alive
Date: Wed, 03 May 2023 02:37:46 GMT
WWW-Authenticate: Basic realm="shipstation"
```

# Type of change 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Functionality change (fix or feature that would cause existing functionality to work differently than before)
- [ ] Configuration change
- [ ] New / updated script
- [ ] Refactoring
- [ ] New tests to existing code

# PR Readiness Checklist
- [ ] Followed [development conventions][1] to the best of my ability
- [ ] Code is documented, particularly public interfaces and hard-to-understand areas
- [ ] Tests are updated / added and all pass
- [ ] Performed a self-review of my own code
- [ ] Acceptance criterias are confirmed by testing changes in UI (or another appropriate way)
- [ ] Confluence documentation is updated, if needed
- [ ] New code does not generate new warnings

[1]: https://agileharbor.atlassian.net/wiki/spaces/DEV/pages/1114130/Conventions

2023-05-03 12:28 UTC, christian-bejarano-skuvault approved these changes

2023-05-03 13:42 UTC, maxim-skuvault submitted a review, later dismissed

2023-05-03 13:48 UTC, reydelleon-skuvault requested changes

2023-05-03 13:48 UTC, reydelleon-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +				ShipStationLogger.Log.Info( "[{Channel}] [{Version}]\tRequest to '{Url}' returned HTTP Error with the response content: '{ResponseContent}'. Request Headers: {RequestMessageHeaders}, Response Hea
Let's change `Channel` to `IntegrationName` so that it is consistent with how we log this piece of data in other places.

2023-05-03 13:48 UTC, reydelleon-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{Channel}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
Let's change `Channel` to `IntegrationName` so that it is consistent with how we log this piece of data in other places.

2023-05-03 14:01 UTC, reydelleon-skuvault approved these changes

2023-05-03 14:11 UTC, christian-bejarano-skuvault submitted a review, later dismissed

2023-05-03 16:13 UTC, maxim-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
>  		private void ThrowIfError( string url, HttpResponseMessage responseMessage, string responseContent )
@maxim-saltanov-skuvault Can we pass the mark from v1 and log it in both places below? Can we also pass the mark into the exception? Otherwise, I don't think the sync failure message in v1 will log the mark, and it currently doesn't even log the tenantId (pending tech debt ticket). So it would be hard to correlate

2023-05-03 16:23 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +				ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tRequest to '{Url}' returned HTTP Error with the response content: '{ResponseContent}'. Request Headers: {RequestMessageHeaders}, Resp
@maxim-skuvault I will change it. This is my PR. Thank you!

2023-05-03 16:36 UTC, maxim-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
>  		private void ThrowIfError( string url, HttpResponseMessage responseMessage, string responseContent )
Since we don't pass/log the mark anywhere in shipStationAccess, logging a truncated ApiKey should work instead.

2023-05-03 18:13 UTC, chris-skuvault approved these changes

2023-05-03 18:18 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
Improving other logs is not part of this ticket.

2023-05-03 18:20 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
>  		private void ThrowIfError( string url, HttpResponseMessage responseMessage, string responseContent )
added truncted api key and referenced GUARD-2930 I created to remove api key information and add SyncRunContext instead

2023-05-03 18:27 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
I added this improvement tp 2930

2023-05-03 18:28 UTC, maxim-skuvault commented on src/Global/GlobalAssemblyInfo.cs
> +[ assembly : AssemblyVersion( "1.5.0.1-alpha" ) ]
This won't build. Can't have "-alpha" here. I would just put a "1.5.0.1" here and then add "-alpha" locally in .build.ps1

2023-05-03 18:33 UTC, Victoria-SV commented on src/Global/GlobalAssemblyInfo.cs
> +[ assembly : AssemblyVersion( "1.5.0.1-alpha" ) ]
I am not sure how to do it locally. As far as I remember, I merge this truck and then publish alpha version package to nugget

2023-05-03 18:34 UTC, maxim-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
@Victoria-SV This is a new log line. We're not enhancing existing logs. It's not a huge refactor to log something like "Response indicates throttling. ApiKey ...." here. Also, like in the other place can we log a truncated ApiKey here.

2023-05-03 18:44 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
This is not new log line and has nothing to do with this tciket.

2023-05-03 18:48 UTC, Victoria-SV commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +			ShipStationLogger.Log.Info( "[{IntegrationName}] [{Version}]\tResponse for apiKey '{ApiKey}' and url '{Uri}':\n{ResetInSeconds} - {IsThrottled}\n{Response}",
Look at the changes above. Maxim Saltanov decided to refactor it and it was not part of the plan.

2023-05-03 21:18 UTC, maxim-skuvault approved these changes

2023-05-04 13:42 UTC, SShumer approved these changes

2023-05-04 13:43 UTC, merged