2021-12-30 GUARD-2302 Location/Weight Sync Failing with Intermittent Service Not Responding Error
skuvault-integrations/shipStationAccess pull request #7
Opened 2021-12-30 14:37 UTC by jlopezskuv

Update service's last network activity time every time before making an API request to the server or after handling the response.

2022-01-03 16:53 UTC, maxim-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +						RefreshLastNetworkActivityTime();
@jlopezskuv , We don't really need this 3rd `RefreshLastNetworkActivityTime` since there's no network activity between it and the 2nd one. Parsing the response shouldn't take hardly any time. Same for other places where you added 3 `RefreshLastNetworkActivityTime` calls

2022-01-03 16:56 UTC, maxim-skuvault reviewed
See comments about redundant new `RefreshLastNetworkActivityTime` calls

2022-01-03 16:56 UTC, maxim-skuvault commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +						RefreshLastNetworkActivityTime();
Same comment as above

2022-01-03 21:03 UTC, jlopezskuv commented on src/ShipStationAccess/V2/Services/WebRequestServices.cs
> +						RefreshLastNetworkActivityTime();
Thanks @maxim-skuvault I have removed the 3 `RefreshLastNetworkActivityTime`

2022-01-03 21:49 UTC, maxim-skuvault approved these changes

2022-01-04 14:49 UTC, jnewman-sv approved these changes

2022-01-05 13:23 UTC, nathan-skuvault approved these changes

2022-01-05 15:32 UTC, maxim-skuvault reviewed
See the comment about MSBuild

2022-01-06 19:58 UTC, maxim-skuvault requested changes
See the comment about MSBuild

2022-01-06 21:44 UTC, jlopezskuv commented on .build.ps1
> +Set-Alias MSBuild16 (Join-Path -Path (Get-VSSetupInstance | Where-Object {$_.DisplayName -eq 'Visual Studio Professional 2019'} | select InstallationPath | Select-Object -first 1).InstallationPath -C
@maxim-skuvault By not specifying the name of visual studio, Get-VSSetupInstance is getting the latest version of MSBuild installed on the computer.

2022-01-11 20:31 UTC, maxim-skuvault approved these changes

2022-02-07 19:14 UTC, nathan-newman65190 approved these changes

2022-02-07 19:14 UTC, nathan-newman65190 commented on .build.ps1
> +
Do we need this here?

2022-02-16 20:22 UTC, jlopezskuv commented on .build.ps1
> +
I was getting errors when trying to build the solution using that framework version. I did change this because Get-VSSetupInstance is getting the latest version of MSBuild installed on the computer. Once I did, the errors went away and I was able to build.

2022-02-18 13:52 UTC, merged